- hosts: all
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present 
    notify: Restart httpd
  
  - name: install git
    yum:
      name: git
      state: present 
    notify: install wget 
     
  handlers: 
  - name: Restart httpd
    service:
      name: httpd
      state: restarted  

  - name: install wget 
    yum:
      name: wget
      state: present